#!/usr/bin/env python3
"""Build the signed, dance-only collection feed for GitHub Pages.

The checked-in archive is an app export.  The publisher creates the smaller
v1 archive understood by CallersCompendium, derives all signed measurements
from the generated bytes, and only then signs the manifest.  No private key
belongs in this repository.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile
from urllib.parse import urlparse

from validate_collection import COMMENTARY_FIELDS, Failure, is_present, load_declaration, validate_archive


ORIGIN = "https://analect.callerscompendium.com"
MANIFEST_PATH = "collections/manifest.json"
SIGNATURE_PATH = "collections/manifest.json.sig"
PINNED_PUBLIC_KEY = "pvJMNnRrOkSoTUEgPtiUxwDobjEpCKQ3TtELzhjsBww="
MANIFEST_SCHEMA = {"major": 1, "minor": 0}
MIN_READER_VERSION = "0.1.0"
COLLECTION_DIR = re.compile(r"^(?P<id>[a-z0-9]+(?:-[a-z0-9]+)*)-(?P<suffix>[0-9]+)$")
SEMVER = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
ALLOWED_TOP_LEVEL = {
    "schemaVersion",
    "exportedAt",
    "choreographers",
    "publishedSources",
    "programs",
    "venues",
    "tags",
    "customFields",
    "dances",
}
NON_EMPTY_V1_TOP_LEVEL = ("programs", "venues", "publishedSources", "tags", "customFields")
SOURCE_METADATA_TOP_LEVEL = {"publishedSources"}
SOURCE_METADATA_DANCE = {"sourceCitations", "provenance"}
V1_CAPABILITIES = {"compositePhraseStructureV1"}


class PublicationFailure(Exception):
    """A publication input or artifact cannot be safely published."""


def _fail(message: str) -> None:
    raise PublicationFailure(message)


def _read_json(path: pathlib.Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        _fail(f"{path}: file not found")
    except json.JSONDecodeError as exc:
        _fail(f"{path}: invalid JSON ({exc})")
    if not isinstance(value, dict):
        _fail(f"{path}: expected a JSON object")
    return value


def _non_empty(value) -> bool:
    return value is not None and value is not False and (
        not isinstance(value, str) or value.strip() != ""
    ) and (not isinstance(value, (list, dict)) or bool(value))


def _strict_semver(value: str, *, field: str) -> str:
    if not isinstance(value, str):
        _fail(f"{field}: expected a string")
    text = value.strip()
    if re.fullmatch(r"[0-9]+", text):
        text = f"{text}.0.0"
    if not SEMVER.fullmatch(text):
        _fail(f"{field}: {value!r} is not SemVer-compatible")
    return text


def _json_bytes(value: object) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        + b"\n"
    )


def _load_metadata(directory: pathlib.Path) -> tuple[dict, dict]:
    metadata = _read_json(directory / "collection.json")
    declaration_path = directory / "permission.json"
    declaration = load_declaration(declaration_path)
    nested = metadata.get("permission", {})
    if nested is not None and not isinstance(nested, dict):
        _fail(f"{directory / 'collection.json'}: permission must be an object")
    if declaration is None and not isinstance(nested, dict):
        _fail(f"{directory}: permission metadata is missing")
    return metadata, declaration or nested


def _permission(metadata: dict, declaration: dict, directory: pathlib.Path) -> dict:
    granted_by = declaration.get("grantedBy") or declaration.get("grantor")
    holder = declaration.get("holder") or granted_by
    basis = declaration.get("basis") or declaration.get("role")
    fields = declaration.get("coversFields", declaration.get("fields", []))
    if not isinstance(granted_by, str) or not granted_by.strip():
        _fail(f"{directory}: permission grantor/grantedBy must be a non-empty string")
    if not isinstance(holder, str) or not holder.strip():
        _fail(f"{directory}: permission holder must be a non-empty string")
    if not isinstance(basis, str) or not basis.strip():
        _fail(f"{directory}: permission basis/role must be a non-empty string")
    if not isinstance(fields, list) or any(
        not isinstance(field, str) or field not in COMMENTARY_FIELDS for field in fields
    ):
        _fail(
            f"{directory}: permission fields must name only commentary fields "
            f"{sorted(COMMENTARY_FIELDS)}"
        )
    if len(set(fields)) != len(fields):
        _fail(f"{directory}: permission fields contain duplicates")
    license_name = metadata.get("license")
    if not isinstance(license_name, str) or not license_name.strip():
        _fail(f"{directory}: collection license must be a non-empty string")
    return {
        "grantor": granted_by.strip(),
        "holder": holder.strip(),
        "basis": basis.strip(),
        "license": license_name.strip(),
        "fields": fields,
    }


def _validate_source_envelope(raw: dict, path: pathlib.Path) -> None:
    unknown = sorted(set(raw) - ALLOWED_TOP_LEVEL)
    if unknown:
        _fail(f"{path}: unknown top-level entities: {', '.join(unknown)}")
    if not isinstance(raw.get("dances"), list) or not raw["dances"]:
        _fail(f"{path}: archive contains no dances")
    if not isinstance(raw.get("choreographers"), list):
        _fail(f"{path}: choreographers must be an array")
    for key in ("programs", "venues", "tags", "customFields"):
        value = raw.get(key, [])
        if value is not None and not isinstance(value, list):
            _fail(f"{path}: top-level {key} must be an array")
        if _non_empty(value):
            _fail(f"{path}: v1 does not permit non-empty top-level {key}")


def _sanitize_archive(raw: dict, path: pathlib.Path, declaration: dict) -> tuple[dict, int]:
    """Map app-only source metadata away; fail on publishable content.

    `publishedSources`, `sourceCitations`, and non-published provenance are
    ingestion metadata.  v1 has no transactional source namespace, so the
    generator explicitly removes those fields.  Commentary is never removed:
    validate_archive checks permission coverage, while custom-field content is
    refused because the consumer rejects it.
    """

    _validate_source_envelope(raw, path)
    try:
        validate_archive(path, declaration)
    except Failure as exc:
        _fail(str(exc))

    dances = []
    ids = set()
    all_choreographers = {}
    for item in raw["choreographers"]:
        if not isinstance(item, dict) or not isinstance(item.get("id"), str):
            _fail(f"{path}: choreographers must have string ids")
        if item["id"] in all_choreographers:
            _fail(f'{path}: duplicate choreographer id "{item["id"]}"')
        all_choreographers[item["id"]] = item
    referenced = set()
    for index, source_dance in enumerate(raw["dances"]):
        if not isinstance(source_dance, dict):
            _fail(f"{path}: dance at index {index} must be an object")
        dance = dict(source_dance)
        dance_id = dance.get("id")
        if not isinstance(dance_id, str) or not dance_id.strip():
            _fail(f"{path}: dance at index {index} is missing a dance id")
        if dance_id in ids:
            _fail(f'{path}: duplicate dance id "{dance_id}"')
        ids.add(dance_id)
        author_ids = dance.get("authorIds", [])
        if not isinstance(author_ids, list) or any(
            not isinstance(author_id, str) or not author_id.strip()
            for author_id in author_ids
        ):
            _fail(f'{path}: dance "{dance_id}" has invalid authorIds')
        referenced.update(author_ids)
        if _non_empty(dance.get("customFields", [])):
            _fail(
                f'{path}: dance "{dance_id}" contains custom-field content; '
                "CallersCompendium v1 cannot import it"
            )
        provenance = dance.get("provenance")
        if isinstance(provenance, dict) and (
            provenance.get("source") == "publishedCollection"
        ):
            _fail(
                f'{path}: dance "{dance_id}" contains embedded '
                "published-collection provenance"
            )
        dance["sourceCitations"] = []
        dance.pop("provenance", None)
        dances.append(dance)

    missing = sorted(referenced - set(all_choreographers))
    if missing:
        _fail(f"{path}: dances reference unknown choreographer id(s): {missing}")
    extra = sorted(set(all_choreographers) - referenced)
    if extra:
        _fail(f"{path}: archive contains unreferenced choreographer id(s): {extra}")

    capabilities = 0
    if any(is_present(dance.get("phraseStructure")) for dance in dances):
        capabilities |= 1
    archive = {
        "choreographers": [all_choreographers[key] for key in sorted(referenced)],
        "customFields": [],
        "dances": dances,
        "exportedAt": raw.get("exportedAt", "1970-01-01T00:00:00.000Z"),
        "programs": [],
        "publishedSources": [],
        "schemaVersion": raw.get("schemaVersion"),
        "tags": [],
        "venues": [],
    }
    if not isinstance(archive["schemaVersion"], int) or archive["schemaVersion"] <= 0:
        _fail(f"{path}: schemaVersion must be a positive integer")
    return archive, capabilities


def validate_publishable_archive(archive: dict, label: str = "archive") -> dict:
    """Validate the exact archive envelope that the app's v1 reader consumes."""

    if not isinstance(archive, dict):
        _fail(f"{label}: expected an object")
    unknown = sorted(set(archive) - ALLOWED_TOP_LEVEL)
    if unknown:
        _fail(f"{label}: unknown top-level entities: {', '.join(unknown)}")
    for key in NON_EMPTY_V1_TOP_LEVEL:
        value = archive.get(key, [])
        if not isinstance(value, list):
            _fail(f"{label}: top-level {key} must be an array")
        if value:
            _fail(f"{label}: v1 does not permit non-empty top-level {key}")
    dances = archive.get("dances")
    if not isinstance(dances, list) or not dances:
        _fail(f"{label}: archive contains no dances")
    choreographers = archive.get("choreographers")
    if not isinstance(choreographers, list):
        _fail(f"{label}: choreographers must be an array")
    choreographer_ids = []
    for item in choreographers:
        if not isinstance(item, dict) or not isinstance(item.get("id"), str):
            _fail(f"{label}: choreographers must have string ids")
        choreographer_ids.append(item["id"])
    if len(set(choreographer_ids)) != len(choreographer_ids):
        _fail(f"{label}: duplicate choreographer id")
    ids = set()
    referenced = set()
    for index, dance in enumerate(dances):
        if not isinstance(dance, dict):
            _fail(f"{label}: dance at index {index} must be an object")
        dance_id = dance.get("id")
        if not isinstance(dance_id, str) or not dance_id.strip():
            _fail(f"{label}: dance at index {index} is missing a dance id")
        if dance_id in ids:
            _fail(f'{label}: duplicate dance id "{dance_id}"')
        ids.add(dance_id)
        authors = dance.get("authorIds", [])
        if not isinstance(authors, list) or any(
            not isinstance(author_id, str) or not author_id.strip()
            for author_id in authors
        ):
            _fail(f'{label}: dance "{dance_id}" authorIds must be an array')
        referenced.update(authors)
        if _non_empty(dance.get("customFields", [])):
            _fail(f'{label}: dance "{dance_id}" contains custom-field content')
        citations = dance.get("sourceCitations", [])
        if not isinstance(citations, list):
            _fail(f'{label}: dance "{dance_id}" sourceCitations must be an array')
        if citations:
            _fail(f'{label}: dance "{dance_id}" contains source citations')
        provenance = dance.get("provenance")
        if isinstance(provenance, dict) and provenance.get("source") == "publishedCollection":
            _fail(f'{label}: dance "{dance_id}" contains embedded published provenance')
    if referenced != set(choreographer_ids):
        _fail(f"{label}: choreographers must be exactly the referenced entities")
    return {
        "danceCount": len(dances),
        "commentaryFields": sorted(
            field
            for dance in dances
            for field in COMMENTARY_FIELDS
            if is_present(dance.get(field))
        ),
        "requiredCapabilities": (
            ["compositePhraseStructureV1"]
            if any(is_present(dance.get("phraseStructure")) for dance in dances)
            else []
        ),
    }


def _directory_identity(directory: pathlib.Path, metadata: dict) -> tuple[str, str]:
    match = COLLECTION_DIR.fullmatch(directory.name)
    if not match:
        _fail(f"{directory}: name must end in a visible numeric version suffix")
    collection_id = metadata.get("collectionId")
    if collection_id != match.group("id"):
        _fail(
            f"{directory}: collectionId {collection_id!r} does not match "
            f"directory identity {match.group('id')!r}"
        )
    version = _strict_semver(metadata.get("version"), field=f"{directory}/version")
    expected = f"{int(match.group('suffix'))}.0.0"
    if version != expected:
        _fail(
            f"{directory}: version {version!r} does not match immutable "
            f"directory suffix -{match.group('suffix')}"
        )
    return collection_id, version


def _config_capabilities(metadata: dict) -> list[str]:
    values = metadata.get("requiresCapabilities", metadata.get("requiredCapabilities", []))
    if not isinstance(values, list) or any(not isinstance(value, str) or not value for value in values):
        _fail("collection capabilities must be a list of non-empty strings")
    if len(set(values)) != len(values):
        _fail("collection capabilities contain duplicates")
    return sorted(set(values))


def _make_record(directory: pathlib.Path) -> dict:
    metadata, declaration = _load_metadata(directory)
    collection_id, version = _directory_identity(directory, metadata)
    title = metadata.get("title")
    if not isinstance(title, str) or not title.strip():
        _fail(f"{directory}: title must be a non-empty string")
    permission = _permission(metadata, declaration, directory)
    raw_path = directory / "archive.json"
    raw = _read_json(raw_path)
    archive, inferred_flag = _sanitize_archive(raw, raw_path, declaration if "coversFields" in declaration else None)
    artifact_info = validate_publishable_archive(archive, str(raw_path))
    inferred = artifact_info["requiredCapabilities"]
    capabilities = _config_capabilities(metadata)
    if inferred and inferred[0] not in capabilities:
        _fail(
            f"{directory}: archive requires capability {inferred[0]!r}, "
            "but collection metadata does not declare it"
        )
    # Keep future declared capabilities, while ensuring the current content's
    # capability is never lost during manifest generation.
    capabilities = sorted(set(capabilities) | set(inferred))
    if inferred_flag and "compositePhraseStructureV1" not in capabilities:
        _fail(f"{directory}: composite phrase structure capability was not propagated")
    return {
        "directory": directory.name,
        "collection_id": collection_id,
        "version": version,
        "title": title.strip(),
        "permission": permission,
        "capabilities": capabilities,
        "supersedes": metadata.get("supersedes"),
        "archive": archive,
    }


def _manifest_entry(record: dict, archive_bytes: bytes) -> dict:
    directory = record["directory"]
    return {
        "id": record["collection_id"],
        "version": record["version"],
        "title": record["title"],
        "archiveUrl": f"{ORIGIN}/collections/{directory}/archive.json",
        "archiveBytes": len(archive_bytes),
        "sha256": hashlib.sha256(archive_bytes).hexdigest(),
        "danceCount": len(record["archive"]["dances"]),
        "license": record["permission"]["license"],
        "permission": record["permission"],
        "requiredCapabilities": record["capabilities"],
        "supersedes": record["supersedes"],
    }


def _validate_lineage(entries: list[dict], records: list[dict]) -> None:
    by_directory = {record["directory"]: record for record in records}
    by_identity = {(record["collection_id"], record["version"]): record for record in records}
    if len(by_identity) != len(records):
        _fail("manifest contains duplicate collection id/version identity")
    for entry, record in zip(entries, records):
        target = entry["supersedes"]
        if target is None:
            continue
        if not isinstance(target, str) or not target:
            _fail(f"{record['directory']}: supersedes must be a collection directory name")
        old = by_directory.get(target)
        if old is None:
            _fail(f"{record['directory']}: supersedes unknown collection {target!r}")
        if old["collection_id"] != record["collection_id"] or _semver_compare(
            old["version"], record["version"]
        ) >= 0:
            _fail(
                f"{record['directory']}: supersedes must point to an older version "
                "of the same collection"
            )


def _semver_compare(left: str, right: str) -> int:
    def key(value: str) -> tuple[int, int, int, tuple[tuple[int, object], ...]]:
        core, _, build = value.partition("+")
        numbers, _, pre = core.partition("-")
        major, minor, patch = (int(part) for part in numbers.split("."))
        identifiers = []
        for identifier in pre.split(".") if pre else []:
            if identifier.isdigit():
                identifiers.append((0, int(identifier)))
            else:
                identifiers.append((1, identifier))
        # A release is higher than every pre-release. Build metadata is ignored.
        return (major, minor, patch, tuple(identifiers))

    a = key(left)
    b = key(right)
    if a[:3] != b[:3]:
        return (a[:3] > b[:3]) - (a[:3] < b[:3])
    a_pre = a[3]
    b_pre = b[3]
    if not a_pre and not b_pre:
        return 0
    if not a_pre:
        return 1
    if not b_pre:
        return -1
    for left_id, right_id in zip(a_pre, b_pre):
        if left_id != right_id:
            return (left_id > right_id) - (left_id < right_id)
    return (len(a_pre) > len(b_pre)) - (len(a_pre) < len(b_pre))


def validate_manifest(manifest: dict, artifact_root: pathlib.Path) -> None:
    if manifest.get("manifestSchema") != MANIFEST_SCHEMA:
        _fail("manifestSchema must be {major: 1, minor: 0}")
    if _strict_semver(manifest.get("minReaderVersion"), field="minReaderVersion") != MIN_READER_VERSION:
        _fail(f"minReaderVersion must be {MIN_READER_VERSION}")
    entries = manifest.get("collections")
    if not isinstance(entries, list) or not entries:
        _fail("manifest collections must be a non-empty array")
    identities = set()
    directory_entries = {}
    for entry in entries:
        required = {
            "id", "version", "title", "archiveUrl", "archiveBytes", "sha256",
            "danceCount", "license", "permission", "requiredCapabilities", "supersedes",
        }
        missing = sorted(required - set(entry))
        if missing:
            _fail(f"manifest entry missing field(s): {missing}")
        if not isinstance(entry["id"], str) or not isinstance(entry["version"], str):
            _fail("manifest entry id and version must be strings")
        identity = (entry["id"], entry["version"])
        if identity in identities:
            _fail(f"manifest contains duplicate collection identity {identity}")
        identities.add(identity)
        _strict_semver(entry["version"], field=f"manifest {identity} version")
        if (
            not isinstance(entry["id"], str)
            or not entry["id"]
            or not isinstance(entry["title"], str)
            or not entry["title"].strip()
            or not isinstance(entry["license"], str)
            or not entry["license"].strip()
        ):
            _fail(f"manifest {identity}: id, title, and license must be non-empty strings")
        if not isinstance(entry["archiveBytes"], int) or entry["archiveBytes"] <= 0:
            _fail(f"manifest {identity}: archiveBytes must be positive")
        if not isinstance(entry["danceCount"], int) or entry["danceCount"] <= 0:
            _fail(f"manifest {identity}: danceCount must be positive")
        if (
            not isinstance(entry["sha256"], str)
            or not re.fullmatch(r"[0-9a-f]{64}", entry["sha256"])
        ):
            _fail(f"manifest {identity}: sha256 must be lowercase hexadecimal")
        if not isinstance(entry["archiveUrl"], str):
            _fail(f"manifest {identity}: archiveUrl must be a string")
        parsed = urlparse(entry["archiveUrl"])
        if (
            parsed.scheme != "https"
            or parsed.netloc.lower() != urlparse(ORIGIN).netloc
            or parsed.query
            or parsed.fragment
            or parsed.username
            or parsed.password
            or parsed.port not in (None, 443)
        ):
            _fail(f"manifest {identity}: archiveUrl is not an immutable allowed HTTPS URL")
        relative = parsed.path.lstrip("/")
        path_parts = relative.split("/")
        directory_match = (
            COLLECTION_DIR.fullmatch(path_parts[1])
            if len(path_parts) == 3 and path_parts[0] == "collections"
            else None
        )
        if (
            not directory_match
            or path_parts[2] != "archive.json"
            or directory_match.group("id") != entry["id"]
            or f"{int(directory_match.group('suffix'))}.0.0" != entry["version"]
        ):
            _fail(f"manifest {identity}: archiveUrl is not a collection archive path")
        directory_entries[path_parts[1]] = entry
        archive_path = artifact_root / relative
        try:
            archive_bytes = archive_path.read_bytes()
        except FileNotFoundError:
            _fail(f"manifest {identity}: archive file is missing at {archive_path}")
        if entry["archiveBytes"] != len(archive_bytes):
            _fail(f"manifest {identity}: archiveBytes does not match generated artifact")
        if entry["sha256"] != hashlib.sha256(archive_bytes).hexdigest():
            _fail(f"manifest {identity}: sha256 does not match generated artifact")
        archive_info = validate_publishable_archive(
            json.loads(archive_bytes.decode("utf-8")), str(archive_path)
        )
        if entry["danceCount"] != archive_info["danceCount"]:
            _fail(f"manifest {identity}: danceCount does not match generated artifact")
        permission = entry["permission"]
        if not isinstance(permission, dict):
            _fail(f"manifest {identity}: permission must be an object")
        for key in ("grantor", "holder", "basis", "license"):
            if not isinstance(permission.get(key), str) or not permission[key].strip():
                _fail(f"manifest {identity}: permission.{key} must be a non-empty string")
        fields = permission.get("fields")
        if (
            not isinstance(fields, list)
            or any(not isinstance(field, str) or field not in COMMENTARY_FIELDS for field in fields)
            or len(set(fields)) != len(fields)
        ):
            _fail(f"manifest {identity}: permission.fields is not exhaustive and valid")
        if permission.get("license") != entry["license"]:
            _fail(f"manifest {identity}: permission.license must match license")
        if not set(archive_info["commentaryFields"]).issubset(fields):
            _fail(f"manifest {identity}: permission does not cover populated commentary")
        capabilities = entry["requiredCapabilities"]
        if (
            not isinstance(capabilities, list)
            or any(not isinstance(capability, str) or not capability for capability in capabilities)
            or len(set(capabilities)) != len(capabilities)
        ):
            _fail(f"manifest {identity}: requiredCapabilities contains duplicates")
        if not set(archive_info["requiredCapabilities"]).issubset(capabilities):
            _fail(f"manifest {identity}: required capabilities were not propagated")
    for entry in entries:
        target = entry["supersedes"]
        if target is None:
            continue
        if (
            not isinstance(target, str)
            or target not in directory_entries
            or directory_entries[target]["id"] != entry["id"]
            or _semver_compare(directory_entries[target]["version"], entry["version"]) >= 0
        ):
            _fail(f"manifest {(entry['id'], entry['version'])}: invalid supersedes lineage")


def _public_key_from_private(key_path: pathlib.Path) -> str:
    with tempfile.NamedTemporaryFile() as public:
        try:
            subprocess.run(
                ["openssl", "pkey", "-in", str(key_path), "-pubout", "-outform", "DER", "-out", public.name],
                check=True,
                capture_output=True,
                text=True,
            )
        except FileNotFoundError:
            _fail("openssl is required for Ed25519 signing but was not found")
        except subprocess.CalledProcessError as exc:
            _fail(f"signing key is not a readable Ed25519 private key: {exc.stderr.strip()}")
        der = pathlib.Path(public.name).read_bytes()
    if len(der) < 32:
        _fail("signing key did not produce an Ed25519 public key")
    return base64.b64encode(der[-32:]).decode("ascii")


def _public_key_der(public_key_base64: str) -> bytes:
    try:
        raw = base64.b64decode(public_key_base64, validate=True)
    except ValueError:
        _fail("public key is not valid base64")
    if len(raw) != 32:
        _fail("Ed25519 public key must contain exactly 32 bytes")
    return bytes.fromhex("302a300506032b6570032100") + raw


def sign_manifest(
    manifest_bytes: bytes,
    *,
    key_path: pathlib.Path | None = None,
    key_text: str | None = None,
    public_key_base64: str = PINNED_PUBLIC_KEY,
) -> str:
    """Return the app-compatible base64 detached signature."""

    temporary_key: pathlib.Path | None = None
    if key_path is None and key_text is None:
        _fail(
            "signing credentials unavailable: set "
            "ANALECT_COLLECTION_SIGNING_KEY or ANALECT_COLLECTION_SIGNING_KEY_FILE"
        )
    if key_path is None:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", delete=False) as key:
            key.write(key_text or "")
            key.flush()
            os.chmod(key.name, 0o600)
            temporary_key = pathlib.Path(key.name)
        key_path = temporary_key
    try:
        derived = _public_key_from_private(key_path)
        if derived != public_key_base64:
            _fail(
                "signing key does not match the CallersCompendium-pinned "
                "published-collection public key"
            )
        with tempfile.NamedTemporaryFile() as source, tempfile.NamedTemporaryFile() as signature:
            source.write(manifest_bytes)
            source.flush()
            try:
                subprocess.run(
                    [
                        "openssl",
                        "pkeyutl",
                        "-sign",
                        "-rawin",
                        "-inkey",
                        str(key_path),
                        "-in",
                        source.name,
                        "-out",
                        signature.name,
                    ],
                    check=True,
                    capture_output=True,
                    text=True,
                )
            except FileNotFoundError:
                _fail("openssl is required for Ed25519 signing but was not found")
            except subprocess.CalledProcessError as exc:
                _fail(f"Ed25519 signing failed: {exc.stderr.strip()}")
            raw_signature = pathlib.Path(signature.name).read_bytes()
        if len(raw_signature) != 64:
            _fail("Ed25519 signing returned an unexpected signature length")
        return base64.b64encode(raw_signature).decode("ascii") + "\n"
    finally:
        if temporary_key is not None:
            temporary_key.unlink(missing_ok=True)


def verify_signature(manifest_bytes: bytes, signature_text: str, public_key_base64: str = PINNED_PUBLIC_KEY) -> bool:
    try:
        signature = base64.b64decode(signature_text.strip(), validate=True)
    except ValueError:
        return False
    if len(signature) != 64:
        return False
    with tempfile.NamedTemporaryFile() as source, tempfile.NamedTemporaryFile() as public, tempfile.NamedTemporaryFile() as sig:
        source.write(manifest_bytes)
        source.flush()
        public.write(_public_key_der(public_key_base64))
        public.flush()
        sig.write(signature)
        sig.flush()
        try:
            result = subprocess.run(
                [
                    "openssl",
                    "pkeyutl",
                    "-verify",
                    "-rawin",
                    "-pubin",
                    "-inkey",
                    public.name,
                    "-in",
                    source.name,
                    "-sigfile",
                    sig.name,
                ],
                capture_output=True,
                text=True,
            )
        except FileNotFoundError:
            _fail("openssl is required for Ed25519 signature verification")
        return result.returncode == 0


def generate(
    collections_root: pathlib.Path,
    output_root: pathlib.Path,
    *,
    signing_key: pathlib.Path | None = None,
    signing_key_text: str | None = None,
    sign: bool = True,
    public_key_base64: str = PINNED_PUBLIC_KEY,
) -> dict:
    directories = sorted(path for path in collections_root.iterdir() if path.is_dir())
    if not directories:
        _fail(f"{collections_root}: no collection directories found")
    records = [_make_record(directory) for directory in directories]
    output_collections = output_root / "collections"
    output_collections.mkdir(parents=True, exist_ok=True)
    entries = []
    for record in records:
        archive_bytes = _json_bytes(record["archive"])
        destination = output_collections / record["directory"] / "archive.json"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(archive_bytes)
        entries.append(_manifest_entry(record, archive_bytes))
    _validate_lineage(entries, records)
    manifest = {
        "manifestSchema": MANIFEST_SCHEMA,
        "minReaderVersion": MIN_READER_VERSION,
        "collections": entries,
    }
    manifest_bytes = _json_bytes(manifest)
    manifest_path = output_collections / "manifest.json"
    manifest_path.write_bytes(manifest_bytes)
    validate_manifest(manifest, output_root)
    signature_path = output_collections / "manifest.json.sig"
    if sign:
        key_text = signing_key_text
        if signing_key is None and key_text is None:
            key_text = os.environ.get("ANALECT_COLLECTION_SIGNING_KEY")
            key_file = os.environ.get("ANALECT_COLLECTION_SIGNING_KEY_FILE")
            if key_file:
                signing_key = pathlib.Path(key_file)
            if signing_key is None and key_text is None:
                _fail(
                    "signing credentials unavailable: set "
                    "ANALECT_COLLECTION_SIGNING_KEY or ANALECT_COLLECTION_SIGNING_KEY_FILE"
                )
        signature_path.write_text(
            sign_manifest(
                manifest_bytes,
                key_path=signing_key,
                key_text=key_text,
                public_key_base64=public_key_base64,
            ),
            encoding="ascii",
        )
    else:
        signature_path.unlink(missing_ok=True)
    return {
        "manifest": manifest_path,
        "signature": signature_path if sign else None,
        "entries": entries,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--collections-root", type=pathlib.Path, default=pathlib.Path("collections"))
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("site"))
    parser.add_argument("--signing-key", type=pathlib.Path)
    parser.add_argument("--no-sign", action="store_true", help="generate artifacts without a signature (local tests only)")
    args = parser.parse_args()
    try:
        result = generate(
            args.collections_root,
            args.output,
            signing_key=args.signing_key,
            sign=not args.no_sign,
        )
    except PublicationFailure as exc:
        print(f"PUBLICATION FAILED: {exc}", file=sys.stderr)
        return 1
    print(f"manifest: {result['manifest']}")
    if result["signature"]:
        print(f"signature: {result['signature']}")
    for entry in result["entries"]:
        print(
            f"{entry['id']} {entry['version']}: "
            f"{entry['danceCount']} dances, {entry['archiveBytes']} bytes, "
            f"{entry['sha256']}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
